# Generated by Django 5.0.6 on 2024-05-16 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='checked',
        ),
        migrations.AddField(
            model_name='todoitem',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='due_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='priority',
            field=models.PositiveSmallIntegerField(default='3'),
        ),
    ]
