# Generated by Django 5.0.6 on 2024-05-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_remove_todoitem_checked_todoitem_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='status',
            field=models.CharField(choices=[('Todo', 'Todo'), ('InProcess', 'In Process'), ('Done', 'Done')], default='Todo', max_length=20),
        ),
    ]
